# Generated by Django 3.0.5 on 2020-04-18 22:26

import re
import uuid

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('registration_number', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Thesis registration number is not valid.', regex=re.compile('[A-Z]\\d{3}'))], verbose_name='Registration number')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('abstract', models.TextField(verbose_name='Abstract')),
                ('pdf_file', models.CharField(max_length=512, null=True, verbose_name='File with thesis')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thesis.Category')),
            ],
            options={
                'verbose_name': 'Thesis',
                'verbose_name_plural': 'Theses',
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_reservations', to='thesis.Thesis', verbose_name='Thesis for borrow')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
