# Generated by Django 3.0.5 on 2020-04-24 14:46

import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('thesis', '0004_auto_20200420_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='published_at',
            field=models.DateField(null=True, verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Pořadí'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='category',
            field=models.ForeignKey(help_text='Corresponding category for thesis.', on_delete=django.db.models.deletion.PROTECT, related_name='thesis_category', to='thesis.Category'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='registration_number',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Thesis registration number is not valid.', regex=re.compile('[A-Z]\\d{3}'))], verbose_name='Registration number'),
        ),
    ]
