# Generated by Django 3.0.5 on 2020-04-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0008_reservation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='reservable',
            field=models.BooleanField(default=True, verbose_name='Reservable'),
        ),
    ]
