# Generated by Django 3.0.5 on 2020-04-27 13:41

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis', '0009_thesis_reservable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='author',
        ),
        migrations.CreateModel(
            name='ThesisAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thesis_author_author', to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thesis_author_thesis', to='thesis.Thesis')),
            ],
            options={
                'verbose_name': 'Thesis author relation',
                'verbose_name_plural': 'Thesis author relations',
                'ordering': ['author', 'created'],
            },
        ),
        migrations.AddField(
            model_name='thesis',
            name='authors',
            field=models.ManyToManyField(related_name='thesis_author', through='thesis.ThesisAuthor', to=settings.AUTH_USER_MODEL, verbose_name='Authors'),
        ),
    ]
