# Generated by Django 3.0.5 on 2020-04-29 22:13

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('thesis', '0010_auto_20200427_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='state',
            field=models.CharField(
                choices=[('created', 'Created'), ('ready_for_submit', 'Ready for submit'), ('submitted', 'Submitted'),
                         ('ready_for_review', 'Ready for reviews'), ('reviewed', 'Reviewed'),
                         ('published', 'Published')], default='created', max_length=32, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='registration_number',
            field=models.CharField(max_length=4, null=True, unique=True, validators=[
                django.core.validators.RegexValidator(message='Thesis registration number is not valid.',
                                                      regex=re.compile('[A-Z]\\d{3}'))],
                                   verbose_name='Registration number'),
        ),
    ]
