# Generated by Django 3.0.6 on 2020-05-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0015_thesis_school_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('created',), 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
    ]
