# Generated by Django 3.0.6 on 2020-05-18 22:49
from django.contrib.auth.models import Group, Permission
from django.db import migrations
from django.db.migrations import RunPython


def add(apps, editor):
    Group.objects.get(name='student').permissions.add(
        Permission.objects.get_by_natural_key('view_reservation', 'thesis', 'reservation')
    )


def remove(apps, editor):
    Group.objects.get(name='student').permissions.remove(
        Permission.objects.get_by_natural_key('view_reservation', 'thesis', 'reservation')
    )


class Migration(migrations.Migration):
    dependencies = [
        ('thesis', '0016_auto_20200518_0102'),
    ]

    operations = [
        RunPython(add, remove)
    ]
