# Generated by Django 3.0.6 on 2020-05-22 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis', '0017_allow_students_view_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='school_class',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('created', 'Waiting for prepare'), ('ready', 'Ready for pickup'), ('running', 'Running'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='created', max_length=32, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thesis_opponent', to=settings.AUTH_USER_MODEL, verbose_name='Opponent'),
        ),
    ]
