# Generated by Django 3.0.6 on 2020-05-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0018_auto_20200522_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='for_user',
            new_name='user',
        ),
    ]
