# Generated by Django 3.0.6 on 2020-05-28 09:16
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('thesis', '0020_auto_20200525_0321'),
    ]

    operations = [
        UnaccentExtension(),
    ]
