# Generated by Django 3.0.6 on 2020-05-28 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0021_auto_20200528_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='submit_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Submit deadline'),
        ),
        migrations.AlterField(
            model_name='thesisauthor',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_author_thesis', to='thesis.Thesis'),
        ),
    ]
