# Generated by Django 3.0.6 on 2020-05-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0022_auto_20200528_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Title'),
        ),
    ]
