# Generated by Django 3.0.6 on 2020-05-29 11:55

from django.db import migrations

from apps.audit.operations import EnableAuditOperation


class Migration(migrations.Migration):
    dependencies = [
        ('thesis', '0023_auto_20200528_2303'),
    ]

    operations = [
        EnableAuditOperation('Thesis'),
        EnableAuditOperation('Reservation'),
    ]
