# Generated by Django 3.0.6 on 2020-05-30 00:42

from django.db import migrations

from apps.audit.operations import EnableAuditOperation


class Migration(migrations.Migration):
    dependencies = [
        ('thesis', '0024_enable_audit'),
    ]

    operations = [
        EnableAuditOperation('ThesisAuthor'),
    ]
