# Generated by Django 3.0.6 on 2020-06-03 09:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0025_enable_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='note',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Additional note'),
        ),
    ]
