# Generated by Django 3.2.14 on 2024-04-03 12:20

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0028_alter_thesis_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='registration_number',
            field=models.CharField(max_length=4, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Thesis registration number is not valid.', regex=re.compile('[A-Za-z]\\d{3,5}'))], verbose_name='Registration number'),
        ),
    ]
