# Generated by Django 3.2.14 on 2024-04-06 16:29

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0029_alter_thesis_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='registration_number',
            field=models.CharField(max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Thesis registration number is not valid.', regex=re.compile('[A-Z]\\d{3,5}'))], verbose_name='Registration number'),
        ),
    ]
