# Generated by Django 3.0.6 on 2020-05-18 01:02

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20200510_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=django_bleach.models.BleachField(verbose_name='Review comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='questions',
            field=django_bleach.models.BleachField(verbose_name='Review questions'),
        ),
    ]
