# Generated by Django 3.0.6 on 2020-05-29 16:40

from django.db import migrations

from apps.audit.operations import EnableAuditOperation


class Migration(migrations.Migration):
    dependencies = [
        ('review', '0006_auto_20200528_1449'),
    ]

    operations = [
        EnableAuditOperation('Review'),
    ]
