# Generated by Django 3.2.14 on 2023-10-23 19:10

import django.contrib.postgres.fields
import django.contrib.postgres.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_enable_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Under average'), (2, 'Average'), (3, 'Over average')], help_text='As value between 1 and 3 inclusive, higher is harder.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade_proposal',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not sufficient'), (2, 'Great'), (3, 'Very well'), (4, 'Excellent')], help_text='As value between 1 and 4 inclusive, higher is better.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Proposed grade'),
        ),
        migrations.AlterField(
            model_name='review',
            name='grades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Not sufficient'), (2, 'Great'), (3, 'Very well'), (4, 'Excellent')], help_text='As value between 1 and 4 inclusive, higher is better.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]), size=None, validators=[django.contrib.postgres.validators.ArrayMinLengthValidator(5), django.contrib.postgres.validators.ArrayMaxLengthValidator(6)], verbose_name='Grades'),
        ),
    ]
