# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 08:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedactions',
            name='changed_fields',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True, verbose_name='Changed fields'),
        ),
        migrations.AlterField(
            model_name='loggedactions',
            name='row_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True, verbose_name='Row data'),
        ),
    ]
