version: '3.3'
services:
  web:
    build: ./django
    command: runserver
    volumes:
      - ./django/:/usr/src/app/
    env_file:
      - django/.env.dev

  webserver:
    build: ./nginx
    command: [nginx-debug, '-g', 'daemon off;']

  webpack:
    build: ./webpack
    command: dev
    ports:
      - 3000:3000
    volumes:
      - ./webpack/src/:/usr/src/app/src
    environment:
      - NODE_ENV=development
      - PUBLIC_PATH=http://${SITE_URL:-localhost}:3000/static/
