# Generated by Django 3.0.5 on 2020-04-19 14:30

import apps.attachment.models.attachment
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thesis', '0002_auto_20200419_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Order')),
                ('identifier', models.CharField(blank=True, choices=[('thesis_text', 'Thesis text'), ('supervisor_review', 'Supervisor review'), ('opponent_review', 'Opponent review')], max_length=128, null=True, unique=True, verbose_name='Identifier')),
                ('allowed_content_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=apps.attachment.models.attachment._default_allowed_content_types, size=None, verbose_name='List of allowed mime/content types')),
            ],
            options={
                'verbose_name': 'Type attachment',
                'verbose_name_plural': 'Types attachments',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file_path', models.CharField(max_length=512, null=True, verbose_name='File with thesis')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_attachment', to='thesis.Thesis', verbose_name='Target thesis')),
                ('type_attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_attachment_attachment', to='attachment.TypeAttachment', verbose_name='Type of attachment')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
