# Generated by Django 3.0.5 on 2020-04-19 23:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeattachment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeattachment',
            name='identifier',
            field=models.CharField(choices=[('thesis_text', 'Thesis text'), ('supervisor_review', 'Supervisor review'),
                                            ('opponent_review', 'Opponent review')], max_length=128, unique=True,
                                   verbose_name='Identifier'),
        ),
    ]
