# Generated by Django 3.0.5 on 2020-04-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0002_auto_20200419_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeattachment',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='typeattachment',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Pořadí'),
        ),
    ]
