# Generated by Django 3.0.5 on 2020-04-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0003_auto_20200424_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeattachment',
            name='identifier',
            field=models.CharField(choices=[('thesis_text', 'Thesis text'), ('thesis_assigment', 'Thesis assigment'), ('supervisor_review', 'Supervisor review'), ('opponent_review', 'Opponent review')], max_length=128, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='typeattachment',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='typeattachment',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Order'),
        ),
    ]
