# Generated by Django 3.0.6 on 2020-05-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0006_auto_20200509_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeattachment',
            name='name',
        ),
    ]
