# Generated by Django 3.0.6 on 2020-05-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200429_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree_after',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Degree after'),
        ),
        migrations.AddField(
            model_name='user',
            name='degree_before',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Degree before'),
        ),
    ]
