# Generated by Django 3.0.6 on 2020-05-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_class',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='School class'),
        ),
    ]
