# Generated by Django 3.0.6 on 2020-05-28 12:49

import apps.accounts.models.managers.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200522_0208'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.managers.user.UserManager()),
            ],
        ),
    ]
