# Generated by Django 3.0.5 on 2020-05-04 20:53

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thesis', '0011_auto_20200429_2213'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('comment', models.TextField(verbose_name='Review comment')),
                ('questions', models.TextField(verbose_name='Review questions')),
                ('difficulty', models.PositiveSmallIntegerField(help_text='As value between 1 and 3 inclusive, higher is harder.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Difficulty')),
                ('grades', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(help_text='As value between 1 and 4 inclusive, higher is better.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]), size=None, validators=[django.contrib.postgres.validators.ArrayMinLengthValidator(5), django.contrib.postgres.validators.ArrayMaxLengthValidator(6)], verbose_name='Grades')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_thesis', to='thesis.ThesisAuthor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
