# Generated by Django 3.0.6 on 2020-05-07 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20200504_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('thesis', 'user'), 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='review',
            name='grade_proposal',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Proposed grade'),
        ),
    ]
