# Generated by Django 3.0.5 on 2020-04-19 23:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('thesis', '0002_auto_20200419_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='abstract',
            field=models.TextField(null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
