# Generated by Django 3.0.5 on 2020-04-25 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis', '0006_auto_20200424_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=positions.fields.PositionField(default=-1, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thesis_opponent', to=settings.AUTH_USER_MODEL, verbose_name='Opponent'),
        ),
    ]
