# Generated by Django 3.0.6 on 2020-05-09 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis', '0012_auto_20200509_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thesis_opponent', to=settings.AUTH_USER_MODEL, verbose_name='Opponent'),
        ),
    ]
