# Generated by Django 3.0.6 on 2020-05-10 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0013_auto_20200509_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_thesis', to='thesis.Thesis', verbose_name='Thesis for borrow'),
        ),
    ]
