# Generated by Django 3.0.6 on 2020-05-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0014_auto_20200510_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='school_class',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='School class'),
        ),
    ]
