# Generated by Django 3.0.6 on 2020-05-18 02:04

from django.db import migrations

from apps.audit.operations import AddAuditOperation


class Migration(migrations.Migration):
    dependencies = [
        ('thesis', '0016_auto_20200518_0102'),
    ]

    operations = [
        AddAuditOperation('Thesis'),
        AddAuditOperation('Reservation'),
    ]
