[project]
name = "thesaurus"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "bleach",
    "Django~=3.2",
    "django-better-admin-arrayfield",
    "django-bleach",
    "django-constance[database]",
    "django-debug-toolbar",
    "django-extensions",
    "django-filter",
    "django-lifecycle==0.7.7",
    "django-loginas",
    "django-mail-queue",
    "django-positions",
    "django-python3-ldap",
    "django-seed",
    "django-stubs",
    "django-weasyprint==1.1.0",
    "django-webpack4-loader",
    "djangorestframework",
    "djangorestframework-stubs",
    "Faker",
    "filetype",
    "funcy",
    "gunicorn",
    "psycopg2-binary",
    "python-decouple",
    "sentry-sdk",
    "setuptools",
    "unidecode",
    "uvicorn",
    "WeasyPrint==52.5",
    "Werkzeug",
    "django-admin-env-notice",
    "openpyxl",
]

[tool.uv]
package = false
