# Generated by Django 3.0.6 on 2020-05-07 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0011_auto_20200429_2213'),
        ('attachment', '0004_auto_20200425_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_thesis', to='thesis.Thesis', verbose_name='Target thesis'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='type_attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_type_attachment', to='attachment.TypeAttachment', verbose_name='Type of attachment'),
        ),
    ]
