# Generated by Django 3.0.6 on 2020-05-18 01:02

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models

import apps.attachment.models.attachment


class Migration(migrations.Migration):
    dependencies = [
        ('attachment', '0007_remove_typeattachment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ('thesis', 'type_attachment__order'), 'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AddField(
            model_name='typeattachment',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='typeattachment',
            name='max_size',
            field=models.BigIntegerField(blank=True, default=5242880, null=True, verbose_name='Max size in bytes'),
        ),
        migrations.AlterField(
            model_name='typeattachment',
            name='allowed_content_types',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(choices=[('application/pdf', 'pdf'), ('image/png', 'png'), ('application/zip', 'zip'), ('application/x-rar-compressed', 'rar'), ('application/x-tar', 'tar'), ('application/gzip', 'gz')], max_length=64), blank=True, default=apps.attachment.models.attachment._default_allowed_content_types, help_text='Available options: application/pdf, image/png, application/zip, application/x-rar-compressed, application/x-tar, application/gzip', size=None, verbose_name='List of allowed mime/content types'),
        ),
        migrations.AlterField(
            model_name='typeattachment',
            name='identifier',
            field=models.CharField(choices=[('thesis_text', 'Thesis text'), ('thesis_assigment', 'Thesis assigment'), ('supervisor_review', 'Supervisor review'), ('opponent_review', 'Opponent review'), ('thesis_poster', 'Thesis poster'), ('thesis_attachment', 'Thesis attachment')], max_length=128, unique=True, verbose_name='Identifier'),
        ),
    ]
