# Generated by Django 3.0.6 on 2020-05-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0009_auto_20200524_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=models.IntegerField(default=0, verbose_name='Size of attachment'),
            preserve_default=False,
        ),
    ]
