# Generated by Django 3.0.6 on 2020-06-03 23:19
from typing import Type

from django.apps.registry import Apps
from django.db import migrations
from django.db.migrations import RunPython


def up(apps: Apps, editor):
    from apps.attachment.models import TypeAttachment

    TA: Type[TypeAttachment] = apps.get_model('attachment.TypeAttachment')

    TA.objects.bulk_create([
        TA(identifier=identifier, order=order)
        for order, (identifier, label) in enumerate(TypeAttachment.Identifier.choices)
    ], ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ('attachment', '0011_enable_audit'),
    ]

    operations = [
        RunPython(up, reverse_code=lambda *a: None)
    ]
