# Generated by Django 3.0.7 on 2020-06-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0012_fill_type_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeattachment',
            name='description',
        ),
    ]
